### ISSUE TITLE
Check -- date of birth is part of data set

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/PresenceChecker#114]
did we request date of birth?
do we need it?

it's missing from data

**Comment by robholmesnz** [comment]
If this is missing and we need it then we need to generate the data for now and document the fact that a "real" solution requires this (as with any other data we find we need but is missing from the requested data set). The target is a full definition of the data required to provide the designed user experience (including the ability to calculate eligibility).

**Comment by mischa-s** [comment]
yes, we have it!
