### ISSUE TITLE
Clarification - displaying issuing state

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/PresenceChecker#119]
an identity has an issuing state, a nationality, and a country of birth

we only display the nationality and the country of birth

Do we want to display which state issued the identity?

**Comment by karynLabPlus** [comment]
Yes we want to show the issuing state - Can you put this above 'Country of birth'? and title it 'Issuing state'

**Comment by robholmesnz** [comment]
@Br3nda @dlouise64  - this looks like it isn't blocked - might be resolved?
