### ISSUE TITLE
EPIC: Presence Checker - Look up a customer and present current and future eligibility

### ISSUE THREAD

**Issue by robholmesnz** [ServiceInnovationLab/PresenceChecker#154]
As a Citizenship Officer
I can look up the information of a customer applying for citizenship (by Grant) by ID and view information about that customer - including travel data, current eligibility, and projected future eligibility 

A/C
- Should be able to look up a customer record by entering a passport number
- That customer's information is presented on the screen (including presence/travel information)
- Includes the result of calculations to determine current eligibility based on presence information (not status information yet) - and predicts future eligibility based on presence data to date (not status yet).

parent of #51
parent of #128
parent of #99
parent of #9

**Comment by CharlotteHinton** [comment]
#51 shipped

**Comment by CharlotteHinton** [comment]
#9 still open
