### ISSUE TITLE
Calendar of future days when you are eligible

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/PresenceChecker#155]
A/C
- [x] call rails service
- [ ] display the next 7 days and their eligibility in the calendar
- [x] the days you are eligible need to be coloured in green
- [x] The surrounding div show eligible/not eligible based on what day you've selected

requires: array of dates when we are eligible to apply

needs #51

**Comment by dlouise64** [comment]
![Screen Shot 2018-12-10 at 3.44.31 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f36b7191a37bf1162f4f5c5e5ecc3c4a4356bcbbd671f3e57862804e0ebf876f5e70c06915a5bed649b901ba228e4fd7e4b58b4cd2f42f67b6d5db1063474f4dcbed5727a19141c95df24fe54d5cad13356ae47e2431.png)
![Screen Shot 2018-12-10 at 3.44.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f36b7191a37bf1162f4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0ebf876f5e70c06915a5bed649b901ba228e4fd7e4b58b4cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe54d5cad123760e5742431.png)

**Comment by robholmesnz** [comment]
@dlouise64 - I assume this is going to be treated as a separately tracked and prioritised enhancement/change to the target for #154 ?
