### ISSUE TITLE
Past days present in NZ by rolling year

### ISSUE THREAD

**Issue by dlouise64** [ServiceInnovationLab/PresenceChecker#156]
As a citizenship officer I would like to see the applicants last 5 years of presence in nz.

A/C
- [x] Retrieve data from the Movement table (in rails)
- [x] It displays the rolling year (see new design)
- [x] Shows the total present days for the rolling year

Brenda will provide the methods (rails)

Updated UI: https://app.atomic.io/d/hy9ElAkBKOkj

**Comment by dlouise64** [comment]
![Screen Shot 2018-12-10 at 3.53.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f36b7191a37bf117284f5a5f5ecc3c4a4356bcbbd671f3e57862804e0ebf876f5e70c06915a5bed649b901ba228e4fd7e4b58b4cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe54c55a0103f6ae67e2431.png)

**Comment by dlouise64** [comment]
![Screen Shot 2018-12-10 at 4.02.03 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5d4e54c8f9d70012f9078a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f36b7191a37cf112294f5f5c5ecc3c4a4356bcbbd671f3e57862804e0ebf876f5e70c06915a5bed649b901ba228e4fd7e4b58b4cd2f42f67b6d5db1063474f4dcbed5727a19041c95df24fe54c55ad163763e4772431.png)

**Comment by ssibbehh** [comment]
Updated UI added

**Comment by joris-rotteveel** [comment]
New UI https://app.atomic.io/d/hy9ElAkBKOkj
