### ISSUE TITLE
Add gender to first column in identity section

### ISSUE THREAD

**Issue by ssibbehh** [ServiceInnovationLab/PresenceChecker#164]
This is to accommodate the addition of the issuing state data

**Comment by Br3nda** [comment]
i can see this - Does it look done?

**Comment by mischa-s** [comment]
I confused things a bit with this ticket... the atomic design showed 
![identities](https://user-images.githubusercontent.com/22373872/49842075-08360780-fe1f-11e8-9df5-f760602de399.png)

so I flagged that we would need to readjust some stuff in the columns to make it work, but actually it is fine I think
