### ISSUE TITLE
Update OF query to send Immigtation status

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/PresenceChecker#199]
As a user of the system, we need to send an applicant's day-by-day immigration status (right to stay indefinitely true/false) to open fisca, so OF can use this to calculate if their applicant "may be authorised" as per the Citizenship Act.

A / C
 - [x] Doesn't include the UI update
 - [x] Query in presence checker includes right to indefinite stay

child of #88
needs #198

**Comment by JacOng17** [comment]
Completed under PR #301
