### ISSUE TITLE
Client ID wrong

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/PresenceChecker#200]
Citizen officers don't care about or understand our primary keys in our database. Displaying that is potentially confusing. The user will recognise only immigation NZ's client numbers

Change from using our internal database primary keys `client.id`, to instead use immigration's client id `client.im_client_id`

**Comment by Br3nda** [comment]
The first one i found is here
![image](https://user-images.githubusercontent.com/12266/49842173-5ea34600-fe1f-11e8-9fb1-560c688d6dff.png)

**Comment by Br3nda** [comment]
Same issue with Identity numbers -- don't use identity.id, that's just our own postgresql primary key.
At display we should use identity.identity_number

**Comment by Br3nda** [comment]
Also, the identity has a `serial_number` - That's what we display when we search - so i think it need to be displayed when we show the client too

**Comment by Br3nda** [comment]
Copying the full data from #2 
This is the data we should be displaying

```
[Clients]
Client ID, File Number

[Identities]
Client ID, Identity No, Surname, First name, Second name,  Third name, Gender, Country of Birth, Nationality, Issuing State, Serial No.

[Movements]
Identity No, Movement (arrival/departure), Carrier Time/Date

[Visas_and_Permits]
Identity No, Visa or Permit, Type, S/M, Date Issued, Start Date, Visa Expiry Date
```

**Comment by mischa-s** [comment]
in that order?

**Comment by Br3nda** [comment]
Here's the result of our phone call -- 
![image](https://user-images.githubusercontent.com/12266/49843276-7a105000-fe23-11e8-8523-63329a84ebdc.png)
