### ISSUE TITLE
PRIORITY 1: Permissions on PresenceChecker Repo

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#203]
Currently anyone with access to this Repo could accidentally delete it.

We need to assign some permissions to ensure this doesn't happen.

**Comment by Br3nda** [comment]
I don't think this was ever true - only the members of our team can delete the repo. -- not everyone with access.

**Comment by joris-rotteveel** [comment]
Dana setup roles, so collaborators can't delete the repo

**Comment by robholmesnz** [comment]
@dlouise64 - sounds like changes you have made (either introduction of roles, of correction of permissions on roles?) means that contractors no longer have access to the settings panel. 
If this is the case this can be closed.
If this isn't the case then let's talk about it before we close this case.
@CharlotteHinton FYI as "opener".
