### ISSUE TITLE
Packaging up UX

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#218]
As the service innovation lab
We need to package up the UX in a way that we can easily pass across to TAM.

A / C
 - ReadMe style document
 - Create something that we can share easily
 - Determine whether we can publish this somewhere
 - Make sure that 'users' are anon.
 - Should adhere to the Public Information Act (e.g. up in Cohesion)

**Comment by karynLabPlus** [comment]
blurring photos that contain identifying information and checking that docs are anon
Creating Readme doc to connect the docs in the folder

**Comment by karynLabPlus** [comment]
Ready for publishing:
https://drive.google.com/open?id=1e3FuBdFVzR_GO9V92YfAfhNqeEq4RNrZ

I'll need someone to show me how to publish to Cohesion once @robholmesnz has ok'd this for publishing
