### ISSUE TITLE
Scenarios for status test cases

### ISSUE THREAD

**Issue by robholmesnz** [ServiceInnovationLab/PresenceChecker#221]
As a Citizenship officer
I need to be confident the application I am using is displaying customer presence and immigration status accurately, and performing eligibility calculations for whether "a minister may authorize citizenship by grant" accurately

As the coder writing the app, I need example test case input (and calculated output) so I know what tests to perform on our PresenceChecker application and any missing parts of the calculation

A / C
- [x] Scenarios for the test cases are defined
- [x] Test cases are implemented
- [ ] Test cases are performing in a way so that I can clearly see if there are any errors
- [ ] We have reliable test cases and we can test against them

child of #88

**Comment by Br3nda** [comment]
We think we already have this

**Comment by karynLabPlus** [comment]
Here's the test case scenarios that I wrote last year. Please review and let me know if there is enough info in here:
https://docs.google.com/document/d/1PXS6Vnpt6Cj5Yn2zJQZAT-YwjuOp2hoG5HUPhLlxp_w/edit?usp=sharing
