### ISSUE TITLE
Movements for some users don't seem to be showing

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#222]
Title: Movements on an identity isn't showing for  some users 9651751807, 1240472497, 6675891634, 1701172794, 9373977424

Expected Result - see a range of different arrival and departure dates 

Actual Result
See attached, could be a possible CSS issue?

**Comment by CharlotteHinton** [comment]
![Screen Shot 2018-12-17 at 10.43.23 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc3adfaa62f720013153b36/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f46b7191a379ef0c2f52415d4dbc30254d58eeb9cb74fce36f34985619e8833b5d75c23b45a8b1844be907ba20894a85e4ee834dc0fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe44d55a5153366e177356e0a.png)

**Comment by mischa-s** [comment]
this data appears to be reflective of that seed data
