### ISSUE TITLE
failing to calculate eligibility for leap days

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/PresenceChecker#225]
details on this openfisca story
https://github.com/ServiceInnovationLab/openfisca-aotearoa/issues/116

needs https://github.com/ServiceInnovationLab/openfisca-aotearoa/issues/116

**Comment by CharlotteHinton** [comment]
Known bug with the logic, agreement between Rob & Brenda to descope

**Comment by CharlotteHinton** [comment]
@dlouise64 are you able to review this? Thanks

**Comment by Br3nda** [comment]
This was fixed oj ooen fisca. Needs testing.

**Comment by mischa-s** [comment]
@Br3nda can you leave some more crumbs about where/how this could be tested?

**Comment by Br3nda** [comment]
When applying on 29 February, openfisca should return a response (instead of a 500 error)

When applying on any 1 March that follows a leap year but does not include a leap year ( leap year + 1, e.g. 2017, 2021, 2025 etc) the result for 1 March should always be identical to the response for 28 February, because the 28 February was one year ago for both 1 March and 29 February.

**Comment by mischa-s** [comment]
![pres-check-Feb-28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa1aea6aed2c00012d0e3bc/125516c66e82c728ace21e0d46f8869f30cf80a18aeab40e8258f2d97b1e653f6b14b1247a80e03cfd1839540d094cad455e0b40f5ffdd7da0b63c728f5c59bfd86c5f66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3824ef898a4e391c00198eed10.png)
![pres-check-March-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa1aea6aed2c00012d0e3bc/125516c66e82c728ace21e0d46f8869f30cf80a18aeab40e895ce297210b76316546b3397f8fe62bab0021435a0d18ae405c5910f8f08f7ff0b03c7088590bbf83645e74d42103eee9dc4be05ce36ade0d97bcae8b4bcae93820e6838d4a3f19071d8bfa4f78.png)

**Comment by mischa-s** [comment]
@Br3nda if I understand you correctly the above screenshots would be wrong, but if I try to logic it they seem correct because Feb 28 is before 29, so isn't counted, whereas Mar 1 is after Feb 29, so includes it?

**Comment by Br3nda** [comment]
Oh thats wrong . When you select  1 march, we should calculate on the day *before* not the day after.

**Comment by Br3nda** [comment]
See conversation in slack with Kirsty where i confirmed that 2 weeks ago. 

For application of 28 February 2017, we must check from 28 February 2016 to 27 February 2018.

That ui display is wrong.

**Comment by mischa-s** [comment]
![feb28-2021.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa1aea6aed2c00012d0e3bc/125516c66e82c728ace21e0d46ee919871dacefbdfbbee01e81fe086264c22703d46f9692587e57aee162d055b5648f8175e5f44fefc8979f4bf3d70984019af80330b2b9b645bf9fa9015ad00bd2a8a4a80b7b58a48c7ed3823ee899d02.png)
![mar1-2021.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa1aea6aed2c00012d0e3bc/125516c66e82c728ace21e0d46e5958872cfd1f9ddb8fd0fe64de29b234324676b5ee17e7283b179eb147f5556591afa47585f46f9f9db79afb73c62964e49bc8f3900299f7744eeaa880dbe06b0218e4a84bfbc8e4bc5ed3b22e199c2.png)

**Comment by mischa-s** [comment]
I think I still need to go one step further with the UI, just wrapping my head around how
