### ISSUE TITLE
Q / A review with SME experts

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#266]
As the Citizenship team
We want to site with the SME (working as part of TAM - Citizenship Eligibility experts)  to run through the app in it's current form, so we can determine whether there are any issues with the rules sets that we've developed for.

A / C
 - [x] Send through the scenarios from first sprint across to SME's to review ahead of the sit down
 - [x] Sit with SME's and take them through the app in it's current form
 - [x] Document in Waffle any issues that need to be resolved

Dependent on #221 being completed

**Comment by CharlotteHinton** [comment]
@karynLabPlus can you please drop the link to the scenarios here please

**Comment by karynLabPlus** [comment]
Scenarios:
https://docs.google.com/document/d/1PXS6Vnpt6Cj5Yn2zJQZAT-YwjuOp2hoG5HUPhLlxp_w/edit?usp=sharing

**Comment by karynLabPlus** [comment]
SME Alistair Yates contacted for meeting on Wednesday - waiting for confirmation

**Comment by karynLabPlus** [comment]
Updated doc with comments by SME
