### ISSUE TITLE
Determine development stack

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#3]
As the Lab team
We need to determine what the best development stack is to deliver this project.

A / C
 - Review options including OpenFisca
 - Update team on recommended approach
 - Peer reviewed by Brenda

**Comment by CharlotteHinton** [comment]
We'll need to work out what we are delivering - to firm up for sure what stack we're using.

Also, what requirements for hosting are being put on us.

**Comment by Br3nda** [comment]
Rails, with somw reactjs components
