### ISSUE TITLE
Add 'Visa Type' column to the movements table UI

### ISSUE THREAD

**Issue by lamorrison** [ServiceInnovationLab/PresenceChecker#311]
As an officer
I want to see the client's visa type for each movement
So I can explain why days they were present in New Zealand do not count towards their eligibility for citizenship

Acceptance Criteria
- [x] All arrival rows in the movements table UI show the visa type
- [x] Departure rows show no visa type (because they are nil)
- [x] Arrival rows will be highlighted using the relevant colours to indicate indefinite status
 
Test cases:
- [x] The Visa Type column is in the Movements table UI
- [x] The table row is highlighted for approval if the Visa type is indefinite
- [x] The table row is highlighted for (not approval) if the Visa type is NOT indefinite
- [x] The table row is not highlighted if the Visa type is nil or empty (this is expected for all departure rows)

**Comment by dlouise64** [comment]
closes #312
