### ISSUE TITLE
Copy importing code from secure laptop

### ISSUE THREAD

**Issue by mischa-s** [ServiceInnovationLab/PresenceChecker#313]
The import code has all been written, it needs to be copied from secure laptop into source control

**Comment by lamorrison** [comment]
Two database migrations will  be copied at the same time. No other code needs to be copied off the laptop.

**Comment by mischa-s** [comment]
Also 

- Migration to allow null true on expiry date in movements table
- Migration to remove uniqueness from Identities

- remove uniquness migration
    up
    remove_index :identities, [:issuing_state_id, :serial_number]
    add_index :identities, [:issuing_state_id, :serial_number]

    down
    remove_index :identities, [:issuing_state_id, :serial_number]
    add_index :identities, [:issuing_state_id, :serial_number], unique: true

**Comment by mischa-s** [comment]
nearly done, just need to double check `Migration to allow null true on expiry date in movements table`
