### ISSUE TITLE
User research: Citizenship Officer

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#40]
As a UX design team we need to
understand what the Citizenship Officer goes through when processing applications
so we can design a better blue sky system for this user

A/C
- Write up documentation
- Run through with TAM for additional information

**Comment by karynLabPlus** [comment]
documentation complete:
https://drive.google.com/drive/folders/1nkU2axhwBgD4aM6uXZZPMEVzsI8l4461
