### ISSUE TITLE
User research: Citizenship by Grant Applicant

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#41]
As a UX design team we need to
understand what the applicants go through when applying for citizenship
so we can design a blue sky system for this user

A/C
- Initial Interview questions complete with hairdresser and scrum master and professional
- Observe filling in the current form
- Interview face to face to get deeper understanding
- Feedback from early sketch ideas
- Yvonne's completed research
- Get additional information from TAM

**Comment by karynLabPlus** [comment]
Booked session with Sissy for Thursday 13th Dec at 1pm, at the Lab. Organizing thank-you vouchers for Sissy's time through Michelle.

**Comment by karynLabPlus** [comment]
Done and anon'd info for sharing here:
https://drive.google.com/open?id=1e3FuBdFVzR_GO9V92YfAfhNqeEq4RNrZ
