### ISSUE TITLE
Sketches for Citizenship Officer (blue sky)

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#42]
As the UX team we need to design sketches for the Citizenship Officer
to use in a testing scenario and presentation of concept to TAM
to determine whether what we've designed is fit for purpose, and to demonstrate what is possible long term approach

A / C
- Demonstrates the process flow of a CO
- Validate what the CO needs to see as part of the process
- The flow aligns with the customer experience at the right points

**Comment by CharlotteHinton** [comment]
Notes transferred from 5 November
We can use the experience and interviews with our first interviewee to create a 'blue sky' prototype interface experience of becoming a citizen. It would be good to also create the experience from the CSO and Citizenship Officer for this blue sky approach.

**Comment by karynLabPlus** [comment]
After meeting with the UX team from Te Ara Manaaki, we have decided not to focus on this piece of work for right now, as they are in the process of working in this area. We are wanting to avoid overlaps of pieces of work. This means the above notes may not apply, but we could just talk to them at a high level.

**Comment by CharlotteHinton** [comment]
Closing this ticket - as captured in Icebox under #224 so we don't forget.
