### ISSUE TITLE
Chore: Documenting our design process as we go

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#43]
As the UX team we need to document the design process 
that contains the steps and decisions along the way
to share with the service design community and other interested parties

A / C
- Living Google doc
- Details key points, surprises, decisions, new things we tried and milestones
- Documents what we have learnt so we can build on this knowledge for future projects
- Take photos (if possible) of research, testing and co-design process with users
- Keep the documentation MVP
- Glossary of terms is added ongoing

**Comment by CharlotteHinton** [comment]
Note from Slack:

Worth expanding on how CO went about matching records.. and capturing all names (and possible variations) in the capture.

**Comment by karynLabPlus** [comment]
All documentation in sharing folder:
https://drive.google.com/open?id=1e3FuBdFVzR_GO9V92YfAfhNqeEq4RNrZ
