### ISSUE TITLE
Wireframes for Citizenship by applicant (blue sky)

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#52]
As the business owner
I want to see the updated wireframes for citizenship by applicant so I can communicate more widely where the direction of the product could go.

A / C
 - Wireframes should incorporate feedback received from stakeholders
 - Wireframes should have commentary written in a way that is accessible
 - Wireframes should clearly and easily show the flow of the proposed approach
 - Should be clickable to show the approach in Atomic

Notes:
Doesn't include testing

**Comment by karynLabPlus** [comment]
After meeting with the UX team from Te Ara Manaaki, there looks like there is quite a lot of overlap in the work they are doing. To mitigate this we will push the blue sky and suggest rule/legislation changes

**Comment by robholmesnz** [comment]
Hi @karynLabPlus - is this done?
