### ISSUE TITLE
Scenarios for presence test cases

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#53]
As a Citizenship officer
I need to be confident the application I am using is displaying customer data, and performing eligibility calculations reliably wrt presence

A / C
 - Scenarios for the test cases are defined
 - Test cases are implemented
 - Test cases are performing in a way whereby I can clearly see if there are any errors

REFERENCE FILE:
https://docs.google.com/document/d/1PXS6Vnpt6Cj5Yn2zJQZAT-YwjuOp2hoG5HUPhLlxp_w/edit?usp=sharing

**Comment by robholmesnz** [comment]
Product Owner assigned size 5 (hadn't been assigned at planning?).

**Comment by Br3nda** [comment]
@CharlotteHinton i don't know why this in blocked.
I think Dana did some test cases, and i did some more, but this story is about getting good tests cases from SMEs

**Comment by Br3nda** [comment]
I see now that waffle is configured to see Help wanted = blocked.
I had used that label for marking things good for the first day of new devs

Let's use a "blocked" label for the blocked column instead.

**Comment by robholmesnz** [comment]
@karynLabPlus is this something you can pick up - define a list of test cases and work with Dana to implement them?

**Comment by karynLabPlus** [comment]
I can draft up some test cases, then sanity check these with @ssibbehh before getting Dana to implement.

**Comment by robholmesnz** [comment]
Focus here should be on presence scenarios. I will create a separate card for scenarios for status.

**Comment by karynLabPlus** [comment]
Document complete, including standard tests with edge cases.

https://docs.google.com/document/d/1PXS6Vnpt6Cj5Yn2zJQZAT-YwjuOp2hoG5HUPhLlxp_w/edit?usp=sharing
