### ISSUE TITLE
Implementing design for displaying travel dates results

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#54]
As the business owner
I want to have the updated screen that reflects the design in atomic,
So that the information is more easily consumable.

A / C
- [x] Doesn't include 'Dates Eligible to Apply' 
- [x] Should be able to click the 'Detail' button to see the travel days
 - [x] Should be able to click the 'Detail' button to collapse the travel days
- [ ] Should be tested

https://app.atomic.io/d/TY60i4Id6HO5 (reference page 9)

Notes:
Movement's table is already in the data set.

**Comment by karynLabPlus** [comment]
we will talk to you about this - not sure what you mean

**Comment by CharlotteHinton** [comment]
@mischa-s @karynLabPlus to review to see whether this is ok in the app.
