### ISSUE TITLE
Reviewing demo dataset

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#60]
As the business owner
I need to know that the data set that has been provided to us can be used or understand any issues around the data provided.

A / C
 - [ ] Review the dataset
 - [ ] Determine steps that would need to take place to make the data useable in our context
 - [ ] Document where multiple records exist for the same identity (e.g. how common is this?)
 - [ ] Document status
 - [ ] Provide feedback
 - [ ] Check point with Product Owner on next steps

depends on #114

Spike - spend a day with the data to determine next steps.

**Comment by robholmesnz** [comment]
Removed dependency on #114 - it is likely we identify other data we need to be able to provide the designed user experience and complete eligibility calculations - we will generate this data for now - and document the gaps.
