### ISSUE TITLE
Confirm applicant details

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#70]
As Contact Center Staff or a Citizenship Officer 
I need to see the Applicants details in the 'Presence Checker'
So I can confirm the passport details are a match

A/C
- By entering the passport number in the Enter details screen I can see the applicants identity details:

- Confirmation passport #
- Surname
- First name(s)
- Second name(s)
- Third name(s)
- Date of birth
- Nationality

- Button 'Next'
- Button 'Enter new ID'

**Comment by Br3nda** [comment]
Can we have more details on what that "Enter new ID" does? Is it to start a new search?

**Comment by robholmesnz** [comment]
Detail in this card has been superseded by the UX designs.
