### ISSUE TITLE
Interface for checking a single person with a passport number

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#8]
As the contact centre staff
I should be able to look up the information of a person by ID
And it returns their information 

 A / C
 - [x] Should be able to enter a passport number
 - [x] That person's information presented on the screen
 - [x] Should bring represent the design

https://docs.google.com/presentation/d/17wZvfOO0UTRuAE_XGEm_KBuY1XBdIAq0QgaZtVb_gpM/edit#slide=id.g47c1588cff_0_136

Dev tasks:
 - [ ] Data model for applicant
 - [ ] Model tests (rspec)
 - [ ]  Feature spec (rspec)
 - [ ] Controller tests, that you must be logged in

**Comment by dlouise64** [comment]
closes #79

**Comment by dlouise64** [comment]
@CharlotteHinton Data, models are being taken over in this #92
