### ISSUE TITLE
EPIC: I need the Citizenship eligibility calculation to cater for an applicants immigration status (not just presence)

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#88]
As the business sponsor
I would like to know that the calculation caters for an applicants status
as part of the result it returns. So I'm provided with a complete picture of the applicant.

A / C
 - The calculation should cater for the number of days in NZ an applicant was on an indefinite visa (not just the number of days)

**Comment by Br3nda** [comment]
I've add the visa/permit end to the data request we've made to immigration .
